### ISSUE TITLE
Warning in Keras

### ISSUE THREAD

**Issue by akshaybabloo** [udacity/CarND-Keras-Lab#7]
In the newer version of Keras `2.0.2`, 

the `nb_epoch` in

```python
history = model.fit(X_normalized, y_one_hot, batch_size=128, nb_epoch=2, validation_split=0.2, verbose=2)
```

is changed to `epochs`

```python
history = model.fit(X_normalized, y_one_hot, batch_size=128, epochs=2, validation_split=0.2, verbose=2)
```

**Comment by andrewpaster** [comment]
Hi thanks for pointing this out. We're still using Keras version 1.0 in the classroom, but I'm updating things to version 2.0 this week. I'm guessing by now you are beyond this part of the class. Also if you use the carnd starter kit, it uses Tensorflow v0.12 and Keras v1. We'll be changing the carnd starter kit to use Tensorflow v1 and Keras v2 soon.

**Comment by mvirgo** [comment]
Now updated to Keras 2 syntax.
